memory_config:
  memory_modules:
    - memory_name: env_variable
      memory_class: VariableMemoryModule
      kwargs:
        variables: {}
    - memory_name: chat_history  
      memory_class: ChatMemoryModule  
      kwargs:  
        n_rounds: 5
        
utility_agents:
  - agent_class: CustomAgent
    agent_name: "Digital Twin Agent"
    agent_description: "Uploads and confirms memory from the user's financial profile."
    config: {}

  - agent_class: CustomAgent
    agent_name: "Categorizer Agent"
    agent_description: "Categorizes user transactions and summarizes total spend per category."
    config: {}

  - agent_class: CustomAgent
    agent_name: "Pattern Analyser Agent"
    agent_description: "Analyzes categorized transactions to detect patterns or anomalies."
    config: {}

  - agent_class: CustomAgent
    agent_name: "Nudge Generator Agent"
    agent_description: "Generates one actionable behavioral nudge based on financial behavior."
    config: {}

  - agent_class: CustomAgent
    agent_name: "Options Generator Agent"
    agent_description: "Creates 2â€“3 financial strategy options based on the user's profile and nudge."
    config: {}

  - agent_class: CustomAgent
    agent_name: "Options Simulator Agent"
    agent_description: "Simulates the financial impact of strategy options using user data."
    config: {}
    
  - agent_class: PlanningAgent
    agent_name: "Debt Management Planning Agent"
    agent_description: "Create a plan to manage debt"
    config:
      output_style: "markdown"
      contexts:  
        - "date"
        - "chat_history" # the chat history upto a certain number of rounds
        - "env_variable"
        - "relevant_chat_history" # the chat history that is relevant to the current query
      self_reflection_config:  
        self_reflection: true   # Whether to enable self-reflection for this agent. Default is false.
        max_attempts: 2 # Maximum number of times the agent can perform self-reflection. Default is 2.
        response_selection_mode: "auto"  # Strategy used to generate the final response after reaching max_attempts. Default is "auto".
        return_internal_reflection_msg: false   # Whether to return internal reflection messages. Default is false.
        
  - agent_class: CustomAgent
    agent_name: "Goal Tracker Agent"
    agent_description: "Break goal to track progress."
    config: {}

  - agent_class: CustomAgent
    agent_name: "Narrative Generator Agent"
    agent_description: "Generates a personalized, story-driven financial summary."
    config: {}


super_agents:
  - agent_class: FlowSuperAgent
    agent_name: "North Twin Master"
    agent_description: "Financial advisor for North Bank"
    config:
      goal: "provides financial help based on input."

      agent_list:
        - agent_name: "Digital Twin Agent"
          next_step:
            - "Categorizer Agent"
            - "Options Generator Agent"
            - "Goal Tracker Agent"
        - agent_name: "Categorizer Agent"
          next_step:
            - "Pattern Analyser Agent"
        - agent_name: "Pattern Analyser Agent"
          next_step:
            - "Nudge Generator Agent"
        - agent_name: "Nudge Generator Agent"
          next_step:
            - "Narrative Generator Agent"
        - agent_name: "Options Generator Agent"
          next_step:
            - "Options Simulator Agent"
        - agent_name: "Options Simulator Agent"
          next_step:
            - "Debt Management Planning Agent"
        - agent_name: "Debt Management Planning Agent"
          next_step:
            - "Narrative Generator Agent"             
        - agent_name: "Goal Tracker Agent"
          next_step:
            - "Narrative Generator Agent"
        - agent_name: "Narrative Generator Agent"

orchestrator:
  agent_list:
    - agent_name: "North Twin Master"